# Generated by Django 4.1 on 2022-08-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='gas_stove',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('A', 'Austin'), ('R', 'Round Rock'), ('P', 'Pflugerville'), ('C', 'Cedar Park')], default='A', max_length=20)),
                ('neighborhood', models.CharField(max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.house')),
            ],
        ),
    ]
