# Generated by Django 4.1 on 2022-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_house_gas_stove_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[('A', 'Austin'), ('R', 'Round Rock'), ('P', 'Pflugerville'), ('C', 'Cedar Park')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='house',
            name='features',
            field=models.ManyToManyField(to='main_app.feature'),
        ),
    ]
